### PR TITLE
Added feature to make Terminal.app a UIElement 

### PR DESCRIPTION
**Pull request by popavo**
I also updated to prefs view to include the setting (https://github.com/popavo/totalterminal-i18n.git).  I originally had the toggle in the status menu but, thought it better to put in the preferences window.

### CODE REVIEW

**Comment by darwin** [comment]
Nice job!

**Comment by gharlan** [comment]
How can I activate this feature? I don't find an option…

**Comment by darwin** [comment]
=> #3

**Comment by gharlan** [comment]
Ah ok, thanks, this works! Love it! :)

**Pull request merged**
